version: '3.4'
services:

  youtube-player-backend:
    container_name: youtube-player-backend
    image: youtube-player-backend:v0.2
    build:
      context: ./backend
    expose:
      - "8081"
    networks:
      youtube-player_network:
        ipv4_address: 10.2.0.2
    restart: on-failure
    tty: true
    env_file: ./addresses.env
    environment:
      - DISPLAY=unix$DISPLAY
      - XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR}
      - PULSE_SERVER=unix:${XDG_RUNTIME_DIR}/pulse/native
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${XDG_RUNTIME_DIR}/pulse:${XDG_RUNTIME_DIR}/pulse
      - /var/lib/dbus:/var/lib/dbus
      - /dev/shm:/dev/shm
      - /usr/bin/dbus-launch:/usr/bin/dbus-launch
    devices:
      - /dev/dri:/dev/dri
      
      
  youtube-player-frontend:
    container_name: youtube-player-frontend
    image: youtube-player-frontend:v0.2
    build:
      context: ./frontend
    expose:
      - "8000"
    networks:
      youtube-player_network:
        ipv4_address: 10.2.0.3
    restart: on-failure
    tty: true
    env_file: ./addresses.env
    
    
networks:
  youtube-player_network:
    ipam:
      config:
        - subnet: 10.2.0.0/16
        